tasks:
  - init: |
      git clone https://github.com/vlang/v && cd v && make && cd ..
      git clone https://github.com/EmmaTheMartian/clockwork
  - command: |
      cd v && ./v symlink && cd ..
      cd clockwork && v install EmmaTheMartian.Maple && v run . install && cd ..
